name: Check Testinfra sample
on:
  push:
  pull_request:
  schedule:
    # Run once per week to ensure that the pipeline is okay.
    - cron: "19 23 * * 0"

permissions:
  contents: read

jobs:
  check:
    name: "Check"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          file: docker/Dockerfile
          push: false
          tags: myimage
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: cd testinfra && python -m venv . && pip install -r requirements.txt

      - name: Run tests
        run: cd testinfra && source bin/activate && py.test -v test.py
